x=int(input("enter a number"))
y=int(input("enter a number"))
print("x is greaterthan y")
print(x+y)
print(x-y)
print(x*y)
print(x%y)
print(x/y)
print(x//y)
print(x**y)
print(x&y)
print(x^y)
print(x|y)

